#!/bin/bash
# Demo: Enhanced Choose-Tree Visual Hierarchy

echo "🎯 Enhanced Session/Project/Window Selector Demo"
echo "==============================================="
echo ""
echo "This demo showcases the visual improvements to smux's session selector"
echo "with enhanced differentiation between projects, sessions, and windows."
echo ""

echo "🎨 Visual Hierarchy Features Applied:"
echo "======================================"
echo ""
echo "📂 Projects (Top Level)"
echo "  • Color: Bold accent (#95E6CB)"
echo "  • Icon: 📂 folder symbol"
echo "  • Format: 'Project Name - X sessions (created time)'"
echo "  • Purpose: Clear project identification"
echo ""
echo "🖥️ Sessions (Under Projects or Standalone)"
echo "  • Color: Standard text (#BFBDB6) with tree connectors"
echo "  • Icon: 🖥️ computer symbol with ├─ tree connector"
echo "  • Format: 'Session Name - X windows [● ACTIVE if attached]'"
echo "  • Purpose: Show session hierarchy and activity status"
echo ""
echo "🪟 Windows (Under Sessions)"
echo "  • Color: Subdued (#565B66) with deeper indentation"
echo "  • Icon: 🪟 window symbol with └─ tree connector"
echo "  • Format: 'Window Name [● if active window]'"
echo "  • Purpose: Show window structure within sessions"
echo ""

echo "🌟 Before vs After Comparison:"
echo "============================="
echo ""
echo "BEFORE (Standard tmux):"
echo "  session1: 2 windows (attached)"
echo "  session2: 1 windows"
echo "  project1: 3 sessions"
echo ""
echo "AFTER (Enhanced smux):"
echo "  📂 project1 - 3 sessions (Wed Oct 15 14:06:52 2025)"
echo "    ├─ 🖥️ frontend - 2 windows ● ACTIVE"
echo "      └─ 🪟 main ●"
echo "      └─ 🪟 tests"
echo "    ├─ 🖥️ backend - 1 windows"
echo "      └─ 🪟 server"
echo "  🖥️ standalone-session - 1 windows"
echo "    └─ 🪟 bash"
echo ""

echo "⚡ Interactive Testing:"
echo "====================="
echo ""
echo "1. Open the Enhanced Session Selector:"
echo "   • Run: smux attach-session -t backend"
echo "   • Press: Ctrl+B then 's'"
echo "   • Navigate with arrow keys"
echo "   • Press Enter to select, 'q' to cancel"
echo ""
echo "2. Open the Enhanced Window Selector:"
echo "   • While in a session, press: Ctrl+B then 'w'"
echo "   • See windows organized under their sessions"
echo "   • Notice active window highlighting"
echo ""

echo "🎯 Key Visual Improvements:"
echo "=========================="
echo ""
echo "✅ Hierarchical Structure:"
echo "   • Clear parent-child relationships"
echo "   • Tree-style connectors (├─ └─)"
echo "   • Proper indentation levels"
echo ""
echo "✅ Visual Differentiation:"
echo "   • Projects: Bold accent color with 📂"
echo "   • Sessions: Standard color with 🖥️"
echo "   • Windows: Subdued color with 🪟"
echo ""
echo "✅ Status Indicators:"
echo "   • Active sessions: ● ACTIVE indicator"
echo "   • Current windows: ● highlight"
echo "   • Consistent accent color (#95E6CB)"
echo ""
echo "✅ Dark Theme Integration:"
echo "   • Matches status bar color scheme"
echo "   • Consistent with selector background"
echo "   • Cohesive visual experience"
echo ""

echo "🚀 Technical Implementation:"
echo "=========================="
echo ""
echo "The enhanced formatting is built directly into smux's choose-tree"
echo "command templates with:"
echo ""
echo "• Custom format strings with tmux color codes"
echo "• Unicode icons and tree connectors"
echo "• Conditional formatting for active states"
echo "• Hierarchical indentation structure"
echo ""
echo "All themes automatically include these enhancements!"
echo ""

echo "💡 Usage Tips:"
echo "============="
echo ""
echo "• Use 'Ctrl+B s' frequently for quick session navigation"
echo "• Look for the ● indicators to find active elements"
echo "• Projects appear at the top level for easy identification"
echo "• Tree structure shows clear relationships"
echo "• Colors match your selected status bar theme"
echo ""

echo "🎨 Color Scheme Reference:"
echo "========================="
echo ""
echo "• Accent Color (#95E6CB): Projects, active indicators"
echo "• Primary Text (#BFBDB6): Session names, main content"
echo "• Secondary Text (#565B66): Window names, metadata"
echo "• Connector Color (#475266): Tree structure lines"
echo "• Background (#0B0E14): Consistent with status bar"
echo ""

echo "✨ This enhancement provides a much clearer understanding"
echo "   of your session structure at a glance!"